format = """
[🭨](fg:primary)\
[󰣇 ](bg:primary fg:on_primary)\
[🭬](bg:secondary fg:primary)\
$directory\
[🭬](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[🭬](fg:tertiary)\
$character
"""

palette = 'colors'

[palettes.colors]
primary = '#f7bb71'
on_primary = '#472a00'
secondary = '#dfc2a2'
on_secondary = '#3f2d17'
tertiary = '#bbcd9e'
on_tertiary = '#273513'

[character]
success_symbol = '[❯](fg:primary)'
error_symbol = '[❯](fg:primary)'

[directory]
style = "fg:on_secondary bg:secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on_tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind )](fg:on_tertiary bg:tertiary)]($style)'
