format = """
┌ [](fg:primary)\
[󰣇 ](bg:primary fg:on_primary)\
[](bg:secondary fg:primary)\
$directory\
[](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[](fg:tertiary)\
$line_break\
└──$character\
"""

palette = 'colors'

[palettes.colors]
primary = '#a7c8ff'
on_primary = '#03305f'
secondary = '#bdc7dc'
on_secondary = '#273141'
tertiary = '#dbbde2'
on_tertiary = '#3e2845'

[character]
success_symbol = '[](fg:primary)'
error_symbol = '[](fg:primary)'

[directory]
style = "fg:on_secondary bg:secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on_tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind )](fg:on_tertiary bg:tertiary)]($style)'
