format = """
┌ [](fg:primary)\
[󰣇 ](bg:primary fg:on_primary)\
[](bg:secondary fg:primary)\
$directory\
[](bg:tertiary fg:secondary)\
$git_branch\
$git_status\
[](fg:tertiary)\
$line_break\
└──$character\
"""

palette = 'colors'

[palettes.colors]
primary = '{{colors.primary.default.hex}}'
on_primary = '{{colors.on_primary.default.hex}}'
secondary = '{{colors.secondary.default.hex}}'
on_secondary = '{{colors.on_secondary.default.hex}}'
tertiary = '{{colors.tertiary.default.hex}}'
on_tertiary = '{{colors.on_tertiary.default.hex}}'

[character]
success_symbol = '[](fg:primary)'
error_symbol = '[](fg:primary)'

[directory]
style = "fg:on_secondary bg:secondary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $branch ](fg:on_tertiary bg:tertiary)]($style)'

[git_status]
style = "bg:tertiary"
format = '[[($all_status$ahead_behind )](fg:on_tertiary bg:tertiary)]($style)'
