# : Manager [[[

[manager]
cwd = { fg = "#eee0d4" }

# Tab
tab_active = { fg = "#472a00", bg = "#f7bb71", bold = true }
tab_inactive = { fg = "#ffddb7", bg = "#2a1700" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#abd16b", bg = "#abd16b" }
marker_cut = { fg = "#d7e9b9", bg = "#d7e9b9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bbcd9e", bg = "#bbcd9e" }

# Count
count_copied = { fg = "#121f02", bg = "#d7e9b9" }
count_cut = { fg = "#121f02", bg = "#d7e9b9" }
count_selected = { fg = "#472a00", bg = "#bbcd9e" }

# Border
border_symbol = "│"
border_style  = { fg = "#f7bb71" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#472a00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f7bb71", fg = "#472a00", bold = true }
normal_alt  = { bg = "#504539", fg = "#d4c4b5" }

# Select mode
select_main = { bg = "#dfc2a2", fg = "#3f2d17", bold = true }
select_alt  = { bg = "#504539", fg = "#d4c4b5" }

# Unset mode
unset_main = { bg = "#bbcd9e", fg = "#273513", bold = true }
unset_alt  = { bg = "#504539", fg = "#d4c4b5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f7bb71", bg = "#403830" }
progress_error = { fg = "#ffb4ab", bg = "#403830" }

# Permissions
permissions_t = { fg = "#ad773b" }
permissions_w = { fg = "#718b47" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#94c445" }
permissions_s = { fg = "#ff951e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f7bb71" }
active = { fg = "#bbcd9e", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f7bb71" }
value = { fg = "#eee0d4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f7bb71", bg = "#472a00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f7bb71" }
title = {}
hovered = { fg = "#d7e9b9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403830" }
cand = { fg = "#f7bb71" }
rest = { fg = "#472a00" }
desc = { fg = "#eee0d4" }
separator = " ▶ "
separator_style = { fg = "#eee0d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eee0d4" }
run = { fg = "#eee0d4" }
footer = { fg = "#3f2d17", bg = "#dfc2a2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bbcd9e" }
title_warn = { fg = "#f7bb71" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eee0d4" },
    { name = "*/", fg = "#f7bb71" },
]

[icon]
dirs = [
    { name = "Code", text = "", fg = "#dfc2a2" },
    { name = "Documents", text = "", fg = "#dfc2a2" },
    { name = "Downloads", text = "", fg = "#dfc2a2" },
    { name = "Music", text = "", fg = "#dfc2a2" },
    { name = "Pictures", text = "", fg = "#dfc2a2" },
    { name = "Videos", text = "", fg = "#dfc2a2" },
    { name = "Sync", text = "", fg = "#dfc2a2" },
]

conds = [
	{ if = "dir", text = "", fg = "#dfc2a2"  },
# 	{ if = "!(dir | link)", text = "", fg = "#f7bb71" },
# 	{ if = "hidden & dir", text = "", fg = "#bbcd9e"  },
]

# : ]]]
