# : Manager [[[

[manager]
cwd = { fg = "#e0e3e8" }

# Tab
tab_active = { fg = "#00344f", bg = "#96ccf8", bold = true }
tab_inactive = { fg = "#cae6ff", bg = "#001e30" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#b176ff", bg = "#b176ff" }
marker_cut = { fg = "#ebdcff", bg = "#ebdcff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d0c0e8", bg = "#d0c0e8" }

# Count
count_copied = { fg = "#201634", bg = "#ebdcff" }
count_cut = { fg = "#201634", bg = "#ebdcff" }
count_selected = { fg = "#00344f", bg = "#d0c0e8" }

# Border
border_symbol = "│"
border_style  = { fg = "#96ccf8" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#00344f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#96ccf8", fg = "#00344f", bold = true }
normal_alt  = { bg = "#41474d", fg = "#c1c7ce" }

# Select mode
select_main = { bg = "#b7c9d9", fg = "#22323f", bold = true }
select_alt  = { bg = "#41474d", fg = "#c1c7ce" }

# Unset mode
unset_main = { bg = "#d0c0e8", fg = "#362b4a", bold = true }
unset_alt  = { bg = "#41474d", fg = "#c1c7ce" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#96ccf8", bg = "#363a3e" }
progress_error = { fg = "#ffb4ab", bg = "#363a3e" }

# Permissions
permissions_t = { fg = "#557ea2" }
permissions_w = { fg = "#7c50bf" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#9443ff" }
permissions_s = { fg = "#319eff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#96ccf8" }
active = { fg = "#d0c0e8", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#96ccf8" }
value = { fg = "#e0e3e8" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#96ccf8", bg = "#00344f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#96ccf8" }
title = {}
hovered = { fg = "#ebdcff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a3e" }
cand = { fg = "#96ccf8" }
rest = { fg = "#00344f" }
desc = { fg = "#e0e3e8" }
separator = " ▶ "
separator_style = { fg = "#e0e3e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0e3e8" }
run = { fg = "#e0e3e8" }
footer = { fg = "#22323f", bg = "#b7c9d9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d0c0e8" }
title_warn = { fg = "#96ccf8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e0e3e8" },
    { url = "*/", fg = "#96ccf8" },
]

[icon]
dirs = [
    { name = "Code", text = "", fg = "#b7c9d9" },
    { name = "Documents", text = "", fg = "#b7c9d9" },
    { name = "Downloads", text = "", fg = "#b7c9d9" },
    { name = "Music", text = "", fg = "#b7c9d9" },
    { name = "Pictures", text = "", fg = "#b7c9d9" },
    { name = "Videos", text = "", fg = "#b7c9d9" },
    { name = "Sync", text = "", fg = "#b7c9d9" },
]

conds = [
	{ if = "dir", text = "", fg = "#b7c9d9"  },
# 	{ if = "!(dir | link)", text = "", fg = "#96ccf8" },
# 	{ if = "hidden & dir", text = "", fg = "#d0c0e8"  },
]

# : ]]]
