hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("~/.config/dotfiles/scripts/random-wallpaper.sh -no-animation")
    --hl.exec_cmd("sleep 0.8 && hyprlock")
    hl.exec_cmd("waybar")
    hl.exec_cmd("sunshine")
    hl.exec_cmd("syncthing --no-browser")
    hl.exec_cmd("vicinae server")
end)
