$terminal = ghostty
$fileManager = ghostty -e yazi
$menu-scripts = ~/.config/vicinae/menus/scripts.sh

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = awww-daemon
exec-once = ~/.config/dotfiles/scripts/random-wallpaper.sh -no-animation
exec-once = sleep 0.8 && hyprlock

exec-once = waybar

exec-once = sunshine
exec-once = syncthing --no-browser

exec-once = vicinae server
